[package]
name = "my_image_resize_crate"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_image_resize = "2.7.3"
image = "0.24.4"
pyo3 = { version = "0.19.1", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
name = "my_image_resize_crate"